### ISSUE TITLE
Transcriber research

### ISSUE THREAD

**Issue by arvedb** [arvedb/SnapScrib#3]
Overview of possible LLM's, API's, libraries etc. for transcribing audio data.

**Comment by mirixy** [comment]
I would argue Whisper is the best way, it can be used locally or in a slightly limited way on groq api. But even if it would be paid, groq should be cheaper than openai api for whisper. I haven't used other transcription APIs.
I could implement something in the evening, should be really quick to do as I already have the code for it.
